name: Nous-Hermes-2-Mistral-7B
repo_id: Crataco/Nous-Hermes-2-Mistral-7B-DPO-imatrix-GGUF
repo_type: model
model_file: nous-hermes-2-mistral-7b-dpo.Q4_K_M.imx.gguf
model_type: mistral
gpu_layers: 33
context_length: 4096
remove_length: 4
batch_size: 256
threads: 0
threads_batch: 0
rope_freq_base: 10000
rope_freq_scale: 1
template: 
  instruct: "<|im_start|>system\n<INSTRUCTION><|im_end|><CONV_HISTORY>"
  user: "\n<|im_start|>user\n<CONV><|im_end|>"
  assistant: "\n<|im_start|>assistant\n<CONV><|im_end|>"
  next: "\n<|im_start|>assistant"
  stop_tokens: ["<|im_end|>", "<|im_start|>"]